### ISSUE TITLE
Maintain the original copyright in the license file

### ISSUE THREAD

**Issue by rafaelfranca** [coup-mobility/activesupport-current_attributes#2]
The code you copied is licensed with the MIT license that requires you to maintain the same copyright notice and the same license body.

See https://choosealicense.com/licenses/mit/

**Comment by pavel-jurasek-joincoup-com** [comment]
@rafaelfranca is this commit https://github.com/coup-mobility/activesupport-current_attributes/commit/1cd6ffc0cfed385e2385c26e68e6403db4039ffa fixing you problem? We do not want to get credit for code from *Rails sorry for that*

**Comment by rafaelfranca** [comment]
Yes! Thank you so much for handling it
